import type { OrderRecord } from '../types';

// ─── Lookup tables ────────────────────────────────────────────────────────────

const FIRST_NAMES = [
  'James','Mary','John','Patricia','Robert','Jennifer','Michael','Linda',
  'William','Barbara','David','Elizabeth','Richard','Susan','Joseph','Jessica',
  'Thomas','Sarah','Charles','Karen','Priya','Ananya','Rohan','Vikram',
  'Sunita','Arjun','Neha','Rahul','Kavita','Aditya','Fatima','Omar',
  'Zara','Hassan','Layla','Ahmad','Sofia','Carlos','Maria','Luis',
  'Ana','Miguel','Elena','Ivan','Natasha','Dmitri','Ingrid','Lars',
  'Mei','Wei','Yuki','Kenji','Hana','Takeshi',
];

const LAST_NAMES = [
  'Smith','Johnson','Williams','Brown','Jones','Garcia','Miller','Davis',
  'Wilson','Anderson','Taylor','Thomas','Jackson','White','Harris','Martin',
  'Thompson','Patel','Shah','Kumar','Sharma','Singh','Mehta','Gupta',
  'Khan','Ali','Hassan','Ahmed','Malik','Sheikh','Fernandez','Rodriguez',
  'Martinez','Lopez','Gonzalez','Chen','Wang','Zhang','Li','Liu',
  'Nguyen','Tran','Kim','Park','Lee','Tanaka','Yamamoto','Sato',
  'Johansson','Eriksson','Andersen','Nielsen',
];

const PRODUCTS = [
  'Wireless Headphones','Laptop Stand','USB-C Hub','Mechanical Keyboard',
  'Ergonomic Mouse','4K Monitor','Webcam HD','Standing Desk Mat',
  'Cable Management Kit','Monitor Light Bar','Portable SSD 1TB','Power Bank 20000mAh',
  'Smart Watch','Bluetooth Speaker','Ring Light','Laptop Sleeve',
  'Docking Station','HDMI Cable 2m','Screen Cleaner Kit','Desk Organizer',
  'Noise Cancelling Earbuds','Gaming Headset','Stream Deck','Capture Card',
  'External GPU','RAM 16GB DDR5','NVMe SSD 2TB','Cooling Pad',
  'Drawing Tablet','Smartphone Stand','LED Strip Lights','Smart Plug',
  'Air Purifier Mini','Coffee Warmer','Cable Clips','Desk Fan',
];

const VALID_STATUSES = ['Completed', 'Pending', 'Failed', 'Refunded', 'Processing'];
const INVALID_STATUSES = ['DONE', 'complete', 'paid', 'success', 'ERROR', 'cancelled', 'N/A', 'Unknown'];

const DOMAINS = [
  'gmail.com','yahoo.com','outlook.com','hotmail.com','icloud.com',
  'protonmail.com','company.com','work.org','business.net','enterprise.io',
];

// ─── Injection rates ──────────────────────────────────────────────────────────
// Tuned so that roughly 80-90% of rows come out fully clean after validation
// (see src/lib/validation.ts). These are independent per-row probabilities,
// not a hardcoded pass/fail outcome — the actual quality score still comes
// entirely from running the validator against whatever gets generated.

const RATES = {
  duplicateOrderId:   0.015,  // reuse an already-assigned Order_ID
  emailMissing:       0.015,
  emailInvalid:       0.010,
  phoneMissing:       0.015,
  phoneInvalid:       0.010,
  dateNonIso:         0.040,  // recognizable but non-ISO format (warning)
  productWhitespace:  0.010,
  nameDistortion:     0.018,  // case/whitespace distortions
  paymentIdMissing:   0.015,
  paymentStatusBad:   0.015,
  paymentMismatch:    0.12,   // reconciliation-only, doesn't affect quality score
};

export const TOTAL_RECORDS = 2000;
const EXACT_DUPLICATE_ROWS = 20; // ~1% — copies live inside the 2000, not appended after

// Bumped whenever the generation logic changes in a way that affects row
// count or content. Compared against a value cached in localStorage on
// startup so a demo dataset generated by an older build (e.g. one that
// produced 2,040 rows) is detected as stale and regenerated automatically,
// without requiring the person to clear browser storage by hand.
export const DEMO_DATASET_VERSION = 2;
export const DEMO_FILE_NAME = 'demo_ecommerce_orders.csv';

// ─── Seeded Random ────────────────────────────────────────────────────────────

class SeededRandom {
  private seed: number;
  constructor(seed: number) { this.seed = seed; }
  next(): number {
    this.seed = (this.seed * 1664525 + 1013904223) & 0xffffffff;
    return (this.seed >>> 0) / 0xffffffff;
  }
  int(min: number, max: number): number {
    return Math.floor(this.next() * (max - min + 1)) + min;
  }
  pick<T>(arr: T[]): T {
    return arr[this.int(0, arr.length - 1)];
  }
  chance(probability: number): boolean {
    return this.next() < probability;
  }
}

// ─── Date Helpers ─────────────────────────────────────────────────────────────

const DATE_FORMATS = [
  (d: Date) => d.toISOString().split('T')[0],                        // 2024-03-15
  (d: Date) => `${d.getMonth() + 1}/${d.getDate()}/${d.getFullYear()}`, // 3/15/2024
  (d: Date) => `${String(d.getMonth() + 1).padStart(2, '0')}/${String(d.getDate()).padStart(2, '0')}/${d.getFullYear()}`, // 03/15/2024
  (d: Date) => `${d.getDate()}-${d.toLocaleString('en', { month: 'short' })}-${d.getFullYear()}`, // 15-Mar-2024
  (d: Date) => d.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), // March 15, 2024
];

function randomDate(rng: SeededRandom): Date {
  const start = new Date('2023-01-01').getTime();
  const end   = new Date('2024-12-31').getTime();
  return new Date(start + rng.next() * (end - start));
}

// ─── Phone Helpers ────────────────────────────────────────────────────────────
// Every "good" format below carries at least 10 digits, matching the
// digit-count threshold in validation.ts.

function generatePhone(rng: SeededRandom): string {
  const formats = [
    `+1-${rng.int(200, 999)}-${rng.int(200, 999)}-${rng.int(1000, 9999)}`,
    `(${rng.int(200, 999)}) ${rng.int(200, 999)}-${rng.int(1000, 9999)}`,
    `${rng.int(2000000000, 9999999999)}`,
    `+44 ${rng.int(1000, 9999)} ${rng.int(100000, 999999)}`,
    `${rng.int(200, 999)}.${rng.int(200, 999)}.${rng.int(1000, 9999)}`,
  ];
  return rng.pick(formats);
}

function badPhone(rng: SeededRandom): string {
  const bads = [
    '123', 'abc-def-ghij', 'N/A', 'Phone',
    `${rng.int(100, 999)}-${rng.int(10, 99)}`, // too short
    '555-1234',                                // missing area code
    'not-a-phone',
  ];
  return rng.pick(bads);
}

// ─── Email Helpers ────────────────────────────────────────────────────────────

function generateEmail(firstName: string, lastName: string, rng: SeededRandom): string {
  const fn = firstName.toLowerCase();
  const ln = lastName.toLowerCase();
  const domain = rng.pick(DOMAINS);
  const patterns = [
    `${fn}.${ln}@${domain}`,
    `${fn}${ln}${rng.int(1, 99)}@${domain}`,
    `${fn[0]}${ln}@${domain}`,
    `${fn}_${ln}@${domain}`,
  ];
  return rng.pick(patterns);
}

function badEmail(rng: SeededRandom): string {
  const bads = [
    'not-an-email', '@nodomain.com', 'user@', 'plaintext',
    'missing@dot', 'user@@domain.com', 'user @gmail.com',
    'N/A', 'email', 'contact',
  ];
  return rng.pick(bads);
}

// ─── Name Helpers ─────────────────────────────────────────────────────────────

function distortName(name: string, rng: SeededRandom): string {
  const distortions: ((s: string) => string)[] = [
    s => s.toUpperCase(),
    s => s.toLowerCase(),
    s => '  ' + s + '  ',
    s => s + ' ',
    s => ' ' + s,
  ];
  return rng.pick(distortions)(name);
}

// ─── Main Generator ───────────────────────────────────────────────────────────

export function generateDemoData(): OrderRecord[] {
  const rng = new SeededRandom(42); // deterministic seed
  const records: OrderRecord[] = [];
  const usedOrderIds: string[] = [];

  const organicCount = TOTAL_RECORDS - EXACT_DUPLICATE_ROWS;

  for (let i = 1; i <= organicCount; i++) {
    const firstName = rng.pick(FIRST_NAMES);
    const lastName  = rng.pick(LAST_NAMES);
    const fullName  = `${firstName} ${lastName}`;
    const product   = rng.pick(PRODUCTS);
    const qty       = rng.int(1, 10);
    const unitPrice = parseFloat((rng.int(499, 29999) / 100).toFixed(2));
    const orderAmt  = parseFloat((qty * unitPrice).toFixed(2));

    // Order ID — occasionally reuse a prior ID to create a duplicate
    let orderId: string;
    if (usedOrderIds.length > 0 && rng.chance(RATES.duplicateOrderId)) {
      orderId = rng.pick(usedOrderIds);
    } else {
      orderId = `ORD-${String(i).padStart(5, '0')}`;
      usedOrderIds.push(orderId);
    }

    const customerId = `CUST-${String(rng.int(1000, 9999)).padStart(4, '0')}`;

    // Date — sometimes a recognizable but non-ISO format
    const date = randomDate(rng);
    const orderDate = rng.chance(RATES.dateNonIso)
      ? rng.pick(DATE_FORMATS.slice(1))(date)
      : DATE_FORMATS[0](date);

    // Email
    let email: string;
    if (rng.chance(RATES.emailMissing)) {
      email = '';
    } else if (rng.chance(RATES.emailInvalid)) {
      email = badEmail(rng);
    } else {
      email = generateEmail(firstName, lastName, rng);
    }

    // Phone
    let phone: string;
    if (rng.chance(RATES.phoneMissing)) {
      phone = '';
    } else if (rng.chance(RATES.phoneInvalid)) {
      phone = badPhone(rng);
    } else {
      phone = generatePhone(rng);
    }

    const productName  = rng.chance(RATES.productWhitespace) ? `  ${product}  ` : product;
    const customerName = rng.chance(RATES.nameDistortion) ? distortName(fullName, rng) : fullName;

    // Payment ID — when missing, no payment was actually recorded, so the
    // payment amount stays blank too rather than showing a fabricated value.
    const hasPayment = !rng.chance(RATES.paymentIdMissing);
    const paymentId  = hasPayment ? `PAY-${String(rng.int(100000, 999999)).padStart(6, '0')}` : '';

    let paymentAmt = orderAmt;
    if (hasPayment && rng.chance(RATES.paymentMismatch)) {
      const delta = rng.pick([-50, -25, -10, 10, 25, 50, 100, -100, -1, 1]);
      paymentAmt = parseFloat((orderAmt + delta).toFixed(2));
    }

    const paymentStatus = rng.chance(RATES.paymentStatusBad)
      ? rng.pick(INVALID_STATUSES)
      : rng.pick(VALID_STATUSES);

    records.push({
      row_number: i,
      Order_ID: orderId,
      Customer_ID: customerId,
      Customer_Name: customerName,
      Email: email,
      Phone: phone,
      Order_Date: orderDate,
      Product: productName,
      Quantity: String(qty),
      Unit_Price: String(unitPrice),
      Order_Amount: String(orderAmt),
      Payment_ID: paymentId,
      Payment_Amount: hasPayment ? String(paymentAmt) : '',
      Payment_Status: paymentStatus,
    });
  }

  // Exact duplicate rows — full copies of earlier organic rows, generated
  // within the 2,000-row budget rather than appended on top of it.
  for (let i = 0; i < EXACT_DUPLICATE_ROWS; i++) {
    const source = records[rng.int(0, organicCount - 1)];
    records.push({ ...source, row_number: organicCount + i + 1 });
  }

  return records;
}
