/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CleanDataRouteImport } from './routes/clean-data'
import { Route as ErrorsRouteImport } from './routes/errors'
import { Route as RawDataRouteImport } from './routes/raw-data'
import { Route as ReconciliationRouteImport } from './routes/reconciliation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CleanDataRoute = CleanDataRouteImport.update({
  id: '/clean-data',
  path: '/clean-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsRoute = ErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const RawDataRoute = RawDataRouteImport.update({
  id: '/raw-data',
  path: '/raw-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconciliationRoute = ReconciliationRouteImport.update({
  id: '/reconciliation',
  path: '/reconciliation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clean-data': typeof CleanDataRoute
  '/errors': typeof ErrorsRoute
  '/raw-data': typeof RawDataRoute
  '/reconciliation': typeof ReconciliationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clean-data': typeof CleanDataRoute
  '/errors': typeof ErrorsRoute
  '/raw-data': typeof RawDataRoute
  '/reconciliation': typeof ReconciliationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clean-data': typeof CleanDataRoute
  '/errors': typeof ErrorsRoute
  '/raw-data': typeof RawDataRoute
  '/reconciliation': typeof ReconciliationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/clean-data' | '/errors' | '/raw-data' | '/reconciliation'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clean-data' | '/errors' | '/raw-data' | '/reconciliation'
  id:
    | '__root__'
    | '/'
    | '/clean-data'
    | '/errors'
    | '/raw-data'
    | '/reconciliation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CleanDataRoute: typeof CleanDataRoute
  ErrorsRoute: typeof ErrorsRoute
  RawDataRoute: typeof RawDataRoute
  ReconciliationRoute: typeof ReconciliationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clean-data': {
      id: '/clean-data'
      path: '/clean-data'
      fullPath: '/clean-data'
      preLoaderRoute: typeof CleanDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors': {
      id: '/errors'
      path: '/errors'
      fullPath: '/errors'
      preLoaderRoute: typeof ErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raw-data': {
      id: '/raw-data'
      path: '/raw-data'
      fullPath: '/raw-data'
      preLoaderRoute: typeof RawDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconciliation': {
      id: '/reconciliation'
      path: '/reconciliation'
      fullPath: '/reconciliation'
      preLoaderRoute: typeof ReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CleanDataRoute: CleanDataRoute,
  ErrorsRoute: ErrorsRoute,
  RawDataRoute: RawDataRoute,
  ReconciliationRoute: ReconciliationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
